version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: note_app
      POSTGRES_PASSWORD: "OaAiXIpwQ-EOwxPFkjdVVOBlhF7JoJQq"
    volumes:
      - note_app_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "U68U9wHcS0lQOE6TA2mgnbdDQe2sMRhc"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  note_app_data:
